// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/connection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Person message
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_proto_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreatePerson
type CreatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	mi := &file_proto_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePersonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonResponse) Reset() {
	*x = CreatePersonResponse{}
	mi := &file_proto_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonResponse) ProtoMessage() {}

func (x *CreatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePersonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAllPersons
type GetAllPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPersonsRequest) Reset() {
	*x = GetAllPersonsRequest{}
	mi := &file_proto_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPersonsRequest) ProtoMessage() {}

func (x *GetAllPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPersonsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPersonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{3}
}

type GetAllPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*Person              `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPersonsResponse) Reset() {
	*x = GetAllPersonsResponse{}
	mi := &file_proto_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPersonsResponse) ProtoMessage() {}

func (x *GetAllPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPersonsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPersonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllPersonsResponse) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

// UpdatePerson
type UpdatePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	mi := &file_proto_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersonRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *UpdatePersonRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type UpdatePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonResponse) Reset() {
	*x = UpdatePersonResponse{}
	mi := &file_proto_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonResponse) ProtoMessage() {}

func (x *UpdatePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePersonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeletePerson
type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_proto_connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonResponse) Reset() {
	*x = DeletePersonResponse{}
	mi := &file_proto_connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonResponse) ProtoMessage() {}

func (x *DeletePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_connection_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePersonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_connection_proto protoreflect.FileDescriptor

const file_proto_connection_proto_rawDesc = "" +
	"\n" +
	"\x16proto/connection.proto\x12\n" +
	"connection\"\x1c\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13CreatePersonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14CreatePersonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14GetAllPersonsRequest\"E\n" +
	"\x15GetAllPersonsResponse\x12,\n" +
	"\apersons\x18\x01 \x03(\v2\x12.connection.PersonR\apersons\"K\n" +
	"\x13UpdatePersonRequest\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"0\n" +
	"\x14UpdatePersonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\")\n" +
	"\x13DeletePersonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14DeletePersonResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xdf\x02\n" +
	"\x11ConnectionService\x12Q\n" +
	"\fCreatePerson\x12\x1f.connection.CreatePersonRequest\x1a .connection.CreatePersonResponse\x12Q\n" +
	"\n" +
	"GetPersons\x12 .connection.GetAllPersonsRequest\x1a!.connection.GetAllPersonsResponse\x12Q\n" +
	"\fUpdatePerson\x12\x1f.connection.UpdatePersonRequest\x1a .connection.UpdatePersonResponse\x12Q\n" +
	"\fDeletePerson\x12\x1f.connection.DeletePersonRequest\x1a .connection.DeletePersonResponseB\x13Z\x11connections/protob\x06proto3"

var (
	file_proto_connection_proto_rawDescOnce sync.Once
	file_proto_connection_proto_rawDescData []byte
)

func file_proto_connection_proto_rawDescGZIP() []byte {
	file_proto_connection_proto_rawDescOnce.Do(func() {
		file_proto_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connection_proto_rawDesc), len(file_proto_connection_proto_rawDesc)))
	})
	return file_proto_connection_proto_rawDescData
}

var file_proto_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_connection_proto_goTypes = []any{
	(*Person)(nil),                // 0: connection.Person
	(*CreatePersonRequest)(nil),   // 1: connection.CreatePersonRequest
	(*CreatePersonResponse)(nil),  // 2: connection.CreatePersonResponse
	(*GetAllPersonsRequest)(nil),  // 3: connection.GetAllPersonsRequest
	(*GetAllPersonsResponse)(nil), // 4: connection.GetAllPersonsResponse
	(*UpdatePersonRequest)(nil),   // 5: connection.UpdatePersonRequest
	(*UpdatePersonResponse)(nil),  // 6: connection.UpdatePersonResponse
	(*DeletePersonRequest)(nil),   // 7: connection.DeletePersonRequest
	(*DeletePersonResponse)(nil),  // 8: connection.DeletePersonResponse
}
var file_proto_connection_proto_depIdxs = []int32{
	0, // 0: connection.GetAllPersonsResponse.persons:type_name -> connection.Person
	1, // 1: connection.ConnectionService.CreatePerson:input_type -> connection.CreatePersonRequest
	3, // 2: connection.ConnectionService.GetPersons:input_type -> connection.GetAllPersonsRequest
	5, // 3: connection.ConnectionService.UpdatePerson:input_type -> connection.UpdatePersonRequest
	7, // 4: connection.ConnectionService.DeletePerson:input_type -> connection.DeletePersonRequest
	2, // 5: connection.ConnectionService.CreatePerson:output_type -> connection.CreatePersonResponse
	4, // 6: connection.ConnectionService.GetPersons:output_type -> connection.GetAllPersonsResponse
	6, // 7: connection.ConnectionService.UpdatePerson:output_type -> connection.UpdatePersonResponse
	8, // 8: connection.ConnectionService.DeletePerson:output_type -> connection.DeletePersonResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_connection_proto_init() }
func file_proto_connection_proto_init() {
	if File_proto_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connection_proto_rawDesc), len(file_proto_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connection_proto_goTypes,
		DependencyIndexes: file_proto_connection_proto_depIdxs,
		MessageInfos:      file_proto_connection_proto_msgTypes,
	}.Build()
	File_proto_connection_proto = out.File
	file_proto_connection_proto_goTypes = nil
	file_proto_connection_proto_depIdxs = nil
}
